### ISSUE TITLE
Getting error: Not implemented: CURLINFO_HEADER_SIZE (2097163) 

### ISSUE THREAD

**Issue by sameerpanjwani** [php-vcr/php-vcr#119] opened 2015-06-09 11:05 UTC
Have been unable to run tests when trying to test the Facebook API calls I'm making using the Facebook PHP SDK. When I do a normal file_get_contents, there is no issue but when I try to record the tests using the actual calls I make in my application, it doesn't work. The file does get created with the actual output but the test stops because of the error.

```php
/**
    * @vcr fb.yml
     */
    public function test_simple_request()
    {
        $result = $this->fb->get('/436652393036916/posts?fields=id,message,from,type,picture,link,name,caption,description,shares,likes.limit(1).summary(true),comments.limit(1).summary(true)');
        $edge = $result->getGraphEdge();
        print_r($edge);
    }
````

Error:

````
Not implemented: CURLINFO_HEADER_SIZE (2097163) 
 C:\xampp\htdocs\mondovoio-trunk\vendor\php-vcr\php-vcr\src\VCR\Util\CurlHelper.php:124
 C:\xampp\htdocs\mondovoio-trunk\vendor\php-vcr\php-vcr\src\VCR\LibraryHooks\CurlHook.php:290
 C:\xampp\htdocs\mondovoio-trunk\vendor\php-vcr\php-vcr\src\VCR\LibraryHooks\CurlHook.php:154
 C:\xampp\htdocs\mondovoio-trunk\vendor\facebook\php-sdk-v4\src\Facebook\HttpClients\FacebookCurl.php:109

````

**Comment by adri** [comment] 2015-06-09 11:31
Great find. I seems to be not implemented in the CurlHelper, should be an easy fix. Not sure if I have time at the moment, any takers?

**Comment by aaa2000** [comment] 2015-06-09 20:46
I think it is already implemented https://github.com/php-vcr/php-vcr/blob/master/src/VCR/Util/CurlHelper.php#L32. But CURLINFO_HEADER_SIZE is not supported for curl < 7.30.0. https://github.com/paypal/PayPal-PHP-SDK/issues/258

So @sameerpanjwani which Curl version do you use?

**Comment by sameerpanjwani** [comment] 2015-06-10 00:25
Copying this as listed in my PHP Info file:

PHP Version 5.5.19
cURL Information 7.39.0
SSL Version	OpenSSL/1.0.1i
ZLib Version	1.2.7.3
libSSH Version	libssh2/1.4.3

My OS: Windows 8.1 and using XAMPP.

**Comment by aaa2000** [comment] 2015-06-10 20:37
I can reproduce it, I will try to resolve it.

**Comment by aaa2000** [comment] 2015-06-10 21:22
@adri Should we store all curl info in the cassette, or only header_size in the cassette or should we add a case in getCurlOptionFromResponse ?

**Comment by adri** [comment] 2015-06-10 21:41
Yeah good question. It is semi related to #112. In less frequent cases it can be handy to have the curl info in the cassette. But in this case I suspect that the header size could be retrieved from the response by using `strlen(HttpUtil:: formatHeadersForCurl($headers))`, or better `mb_strlen` if available.

@sameerpanjwani 
For a quick fix, try using `FacebookGuzzleHttpClient` like described here https://github.com/facebook/facebook-php-sdk-v4/blob/febedbe6b02d790529f277efcd057fd386d22ba5/tests/bootstrap.php#L27

**Comment by aaa2000** [comment] 2015-06-13 20:59
@sameerpanjwani can you try with the fix of PR #121 ?

**Comment by sameerpanjwani** [comment] 2015-06-14 04:49
Yes it works now! Thanks :+1: 

When will this be merged?

**Comment by adri** [comment] 2015-06-14 11:35
Merged :-)

**Closed by adri** 2015-06-14 11:35 UTC
