### ISSUE TITLE
Segmentation fault with large JSON responses when using YAML storage

### ISSUE THREAD

**Issue by justincy** [php-vcr/php-vcr#125] opened 2015-06-24 17:47 UTC
I get a segmentation fault when recording/replaying requests that have a large JSON body in the response. I believe it's an issue with the symfony YAML parser (see https://github.com/symfony/symfony/issues/15070) but I'm posting it here too just in case it helps someone with a similar problem.

JSON storage does not experience this issue.

**Comment by adri** [comment] 2015-06-24 19:50
Did you try switching to json for storage? `VCR::configure->setStorage('json')`

**Comment by justincy** [comment] 2015-06-24 19:53
Yes. JSON storage does not seg fault. That's the solution I'm going with (it also appears to be faster, at least for my use case).

**Comment by adri** [comment] 2015-06-24 19:57
Yeah indeed JSON is almost always faster. 

I'm sorry, I didn't read your initial description properly where you mentioned already that JSON works.

**Comment by justincy** [comment] 2015-06-24 20:26
> Yeah indeed JSON is likely always faster.

That should probably be documented. Or JSON should be the default storage mechanism. Or both.

**Comment by aaa2000** [comment] 2015-06-25 13:09
Is not the same issue https://github.com/php-vcr/php-vcr/issues/84 ?

**Comment by aaa2000** [comment] 2015-06-25 13:21
and this issue https://github.com/php-vcr/php-vcr/issues/104 too ?

>
the problem is fixed by increasing pcre.backtrack_limit in php.ini

**Comment by justincy** [comment] 2015-06-26 14:59
@aaa2000 Yeah you're right. Sorry I missed that.

**Comment by adri** [comment] 2015-06-28 10:42
Added to documentation http://php-vcr.github.io/documentation/configuration/#storage thanks to @aaa2000.

**Closed by adri** 2015-06-28 10:42 UTC
