### ISSUE TITLE
PHP7.4 & guzzle

### ISSUE THREAD

**Issue by janvernieuwe** [php-vcr/php-vcr#289] opened 2019-12-02 09:34 UTC
Since upgrading to php7.4 im getting

```
ParseError : syntax error, unexpected end of file, expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:197
```
I have noticed this on multiple projects. I'll try to look into this later today, but as of now it's not really usable on php 7.4.

I only get this error when VCR is turned on.

**Comment by JapSeyz** [comment] 2019-12-10 10:49
Did you dig further into this?

**Comment by janvernieuwe** [comment] 2019-12-10 14:11
I tried, but there is some really weird issue going on. It almost seems that files are not completely loaded after x lines. It's very strange. If I find something, I'll make it known here.

**Comment by brunowowk** [comment] 2019-12-10 14:59
Maybe it's a regression on this php 7.4 bug: https://bugs.php.net/bug.php?id=78406

Tried finding the exact spot where it occurs with xdebug and it seems to happen when the file is included.
The CodeTransform works as expected, but somehow it seems that part of the stream is ignored, probably because the code transform increases the file size and the old file size is considered.

Looks like It's being reproduced on travis on the 7.4 test suite on #290:
https://travis-ci.org/php-vcr/php-vcr/jobs/619582578?utm_medium=notification&utm_source=github_status

Just by having this on the bootstrap it breaks the test suite:
```
\VCR\VCR::turnOn();
\VCR\VCR::turnOff();
```
When commenting it the tests run, breaking in other spots, and reporting several errors of this kind when composer tries to autoload some classes:
```
ParseError: syntax error, unexpected end of file in php-vcr/src/VCR/Util/HttpClient.php:35
Stack trace:

#0 php-vcr/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile(...
```

By commenting `$this->enableLibraryHooks();` on `\VCR\Videorecorder::turnOn()` I get no more syntax errors. So it's most definitely a problem on the stream processing used by those hooks

It's either a bug on core or some undocumented change on streams that broke the stream processing.
The only related change I could find was: https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.stream-wrappers 
But that doesn't seem to explain what we see going on here.

**Comment by morozov** [comment] 2019-12-14 17:41
[Bug #78406](https://bugs.php.net/bug.php?id=78406) is closed and according to https://3v4l.org/jEMEE is no longer reproducible although underlying logic and the symptoms look very similar.

Could anyone who is better familiar with the VCR internals rework the code snippet mentioned above to reproduce the issue in isolation from the VCR itself? Then it could be reported and fixed upstream.

**Comment by janvernieuwe** [comment] 2019-12-30 14:03
I have a feeling it is related to this issue https://github.com/goaop/framework/issues/426
Unfortunately no fix found yet.

**Comment by morozov** [comment] 2019-12-30 15:25
> Unfortunately no fix found yet.

Could you please try reproducing the bug in isolation from the rest of the VCR code?

**Comment by janvernieuwe** [comment] 2019-12-31 09:24
I tried to remove as much as possible.
https://github.com/janvernieuwe/php-vcr-debug

I'm now looking at the patchwork library (https://github.com/antecedent/patchwork), where the streamprocessor of vcr seems to be based, to see if I can find a solution there.

**Comment by morozov** [comment] 2019-12-31 15:48
@janvernieuwe this is good progress! At [bugs.php.net](https://bugs.php.net/), they accept a code sample that reproduces the problem. The same could be evaluated at [3v4l.org](http://3v4l.org/). Could you put all the code in one file and potentially remove some more irrelevant pieces?

Once it's reproducible in a single PHP script, we can file a bug.

**Comment by janvernieuwe** [comment] 2020-01-03 22:48
I'll take a look on monday, but it happens on include, so the file needs to to be separate in the testing.

**Comment by janvernieuwe** [comment] 2020-01-06 08:34
Gets even weirder now. When I add the classes into the file itself instead of including them, the error doesn't seem to be occurring.

I left the `run.php` in place and added a `run2.php` where the classes are included.
Weirdness.

**Comment by morozov** [comment] 2020-01-06 16:53
I've filed the bug and referenced the repository above: https://bugs.php.net/bug.php?id=79072.

**Comment by janvernieuwe** [comment] 2020-01-07 08:23
Nice, seems like an easy enough fix!

**Comment by carusogabriel** [comment] 2020-01-07 08:47
@janvernieuwe @morozov I'll take a look into this during this week, I want first ensure that #292 and #256 don't get conflict with it :)

**Comment by morozov** [comment] 2020-01-07 15:53
> Nice, seems like an easy enough fix!

Please see #293.

**Comment by morozov** [comment] 2020-01-07 15:56
>  I'll take a look into this during this week, I want first ensure that #292 and #256 don't get conflict with it :)

Thanks, @carusogabriel. Since #292 is about bumping the minimal required PHP version, I'd like to make sure that the fix for this issue is released before the version is bumped so that PHPBrew can use it before it bumps its own PHP requirement.

**Comment by danielbecker** [comment] 2020-01-30 10:36
I'd like to bump the issue as we're having trouble with it, as well.

**Comment by bomas13** [comment] 2020-01-30 13:26
Unfortunately for me this fixes the initial error like `syntax error, unexpected end of file...` but the test seems to get into an endless loop and runs for 60min without a timeout. Does anyone have a similar behaviour or better yet a solution for it?

**Comment by carusogabriel** [comment] 2020-01-30 14:11
I'm on vacation until February 17th. Once I'm back, I'll take a look at this 👍

**Comment by bomas13** [comment] 2020-01-30 14:28
Ah ok. Have a nice holiday!

Just for your information: After updating PHP to 7.4.2. I'm getting the following error (incl. fix from morozov):
```
ErrorException : Trying to access array offset on value of type null
 /app/vendor/php-vcr/php-vcr/src/VCR/Storage/Yaml.php:61
 /app/vendor/php-vcr/php-vcr/src/VCR/Storage/Yaml.php:124
 /app/vendor/php-vcr/php-vcr/src/VCR/Cassette.php:71
 /app/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php:223
 /app/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php:291
 /app/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:204
 /app/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:154
 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php:40
 /app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:28
 /app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:51
 /app/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php:37
 /app/vendor/guzzlehttp/guzzle/src/Middleware.php:29
 /app/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php:70
 /app/vendor/guzzlehttp/guzzle/src/Middleware.php:59
 /app/vendor/guzzlehttp/guzzle/src/HandlerStack.php:71
 /app/vendor/guzzlehttp/guzzle/src/Client.php:361
 /app/vendor/guzzlehttp/guzzle/src/Client.php:163
 /app/vendor/guzzlehttp/guzzle/src/Client.php:183
 /app/vendor/guzzlehttp/guzzle/src/Client.php:96
 /app/tests/Feature/VcrTest.php:20
```

Without the fix and 7.4.2 it behaves like in the first comment

**Comment by bomas13** [comment] 2020-01-31 08:10
We could find a solution for the exception.
The problem with my endless loop was not vcr related.

**Comment by bomas13** [comment] 2020-02-17 11:31
after I switched from my vanilla curl usage to guzzle I run into issues that seem to related to the steam_wrapper issues again. My tests are all getting green, but after PHPUnit prints out the test summary, it won't quit the application successfully. If I run a couple of tests that do not use VCR this behavior doesn't come up. (See the Screenshot. The first test lines are aborted after several minutes of doing nothing [See the `^C`]. The second line runs as expected and gets finished by itself correctly). 

It's a little bit frustrating, but changing all tests from VCR to Mockery will take too much time as well. 

Please please please get VCR working again. Thank you.

![Screenshot](https://user-images.githubusercontent.com/4661591/74650099-3b8dc800-5181-11ea-9c82-f153800f76ba.png)

**Comment by danielbecker** [comment] 2020-02-20 07:09
Hey guys, any update here? We could really need a working version for php 7.4. I'm happy to have a look myself if you could point me at least into the right direction?

**Comment by morozov** [comment] 2020-02-20 07:24
@danielbecker please see https://github.com/php-vcr/php-vcr/pull/293#issuecomment-574749637.

**Comment by danielbecker** [comment] 2020-02-20 08:01
Thanks for the response @morozov. As @bomas13 mentioned, phpunit doesn't terminate. Even with the patch applied.

**Closed** 2020-05-22 17:28 UTC
Labels: Bug
